
"""""""""""""""
" vim basic
"""""""""""""""
set nocompatible
set shortmess=atI
set nobackup
set noerrorbells
"set nowrap
"set background=dark
"set backspace=2
"set cursorline
"set novisualbell
set confirm
set noswapfile
set history=50
set number
set ruler
set laststatus=2
"set showcmd
set cmdheight=2

filetype plugin indent on
syntax on
"colorscheme desert
colorscheme murphy

" search
set ignorecase
set hlsearch
set incsearch

" fold
set foldenable 
set foldmethod=manual

" space & tab
set expandtab
set tabstop=4  
set softtabstop=4
set shiftwidth=4  


